# Generated by Django 3.0.8 on 2020-07-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='image',
        ),
    ]
